spring:
  mustache:
    check-template-location: false
  application:
    name: ToDoList

  datasource:
    username: laststap
    url: jdbc:postgresql://localhost:5432/toDoList
    password: lastPasswordForToDoList
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
  writer-with-default-pretty-printer: true

jwt:
  secret: ${JWT_SECRET:e0de953b-72ab-474c-8fb8-bed8a6128ba1}
  ttl-millis: 43200000
